CREATE TABLE IF NOT EXISTS events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        VARCHAR(255) NOT NULL DEFAULT '',
    venue       VARCHAR(255) NOT NULL DEFAULT '',
    city        VARCHAR(255) NOT NULL DEFAULT '',
    country     VARCHAR(255) NOT NULL DEFAULT '',
    description VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS photos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     VARCHAR(255) NOT NULL DEFAULT '',
    url           VARCHAR(255) NOT NULL DEFAULT '',
    display_order INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS booking_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL DEFAULT '',
    email        VARCHAR(255) NOT NULL DEFAULT '',
    event        VARCHAR(255) NOT NULL DEFAULT '',
    date         VARCHAR(255) NOT NULL DEFAULT '',
    message      TEXT         NOT NULL DEFAULT '',
    source       VARCHAR(255) NOT NULL DEFAULT '',
    language     VARCHAR(255) NOT NULL DEFAULT '',
    status       VARCHAR(255) NOT NULL DEFAULT 'new',
    reply        TEXT,
    submitted_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS unavailable_dates (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date     VARCHAR(255) NOT NULL DEFAULT '',
    end_date VARCHAR(255),
    note     VARCHAR(255)
);
