CREATE TABLE mixes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        VARCHAR(255) NOT NULL DEFAULT '',
    url              VARCHAR(255) NOT NULL DEFAULT '',
    title            VARCHAR(255) NOT NULL DEFAULT '',
    release_year     INT          NOT NULL DEFAULT 0,
    style            VARCHAR(255) NOT NULL DEFAULT '',
    event            VARCHAR(255) NOT NULL DEFAULT '',
    city             VARCHAR(255) NOT NULL DEFAULT '',
    duration_seconds INT          NOT NULL DEFAULT 0,
    display_order    INT          NOT NULL DEFAULT 0
);
