CREATE TABLE external_mixes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    embed_url    VARCHAR(1000) NOT NULL DEFAULT '',
    embed_type   VARCHAR(50)   NOT NULL DEFAULT '',
    title        VARCHAR(255)  NOT NULL DEFAULT '',
    release_year INT           NOT NULL DEFAULT 0,
    style        VARCHAR(500)  NOT NULL DEFAULT '',
    event        VARCHAR(255)  NOT NULL DEFAULT '',
    city         VARCHAR(255)  NOT NULL DEFAULT ''
);

INSERT INTO external_mixes (embed_url, embed_type, title, release_year, style, event, city) VALUES
(
    'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/dj_sabi/proudtobeukrainian&color=%230066ff&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false',
    'soundcloud',
    '#proudtobeukrainian',
    2025,
    'Ukrainian',
    '',
    'Frankfurt'
),
(
    'https://www.youtube.com/embed/slIsj_NFgG0',
    'youtube',
    'Live Mix @ ccStudio',
    2022,
    'Afrobeats, RnB, Dancehall, Baile Funk, Amapiano, Twerk, House',
    'Live Mix ccStudio',
    'Frankfurt'
),
(
    'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/dj_sabi/ahmix&color=%230066ff&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false',
    'soundcloud',
    'AHmix',
    2019,
    'Afrohouse, Afrobeats, RnB, Hip-Hop, House, Baile Funk',
    '',
    'Kyiv'
),
(
    'https://player-widget.mixcloud.com/widget/iframe/?hide_cover=1&feed=%2Fsabiabdulalieva%2Fsabi-live-playtv-29042015%2F',
    'mixcloud',
    'Live @ PlayTV',
    2015,
    'RnB, Hip-Hop, Trap',
    '',
    'Kyiv'
),
(
    'https://www.youtube.com/embed/3pKeGlxPikk',
    'youtube',
    'Live @ PlayTV',
    2014,
    'RnB, Hip-Hop, Trap, Twerk, Moombahton, Dancehall',
    'Play TV',
    'Kyiv'
),
(
    'https://player-widget.mixcloud.com/widget/iframe/?hide_cover=1&feed=%2Fsabiabdulalieva%2Ffav-songz-mistery-edition%2F',
    'mixcloud',
    'Fav Songz vol.2 Mystery Edition',
    2013,
    'Afrohouse, Afrobeats',
    '',
    'Kyiv'
);
